// Code generated by MockGen. DO NOT EDIT.
// Source: context.go
//
// Generated by this command:
//
//	mockgen -destination=context_mock_test.go -package=telestage_test -source=context.go
//

// Package telestage_test is a generated GoMock package.
package telestage_test

import (
	reflect "reflect"

	tgbotapi "github.com/eli-l/telegram-bot-api/v7"
	gomock "go.uber.org/mock/gomock"
)

// MockContext is a mock of BotContext interface.
type MockContext struct {
	ctrl     *gomock.Controller
	recorder *MockContextMockRecorder
}

// MockContextMockRecorder is the mock recorder for MockContext.
type MockContextMockRecorder struct {
	mock *MockContext
}

// NewMockContext creates a new mock instance.
func NewMockContext(ctrl *gomock.Controller) *MockContext {
	mock := &MockContext{ctrl: ctrl}
	mock.recorder = &MockContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContext) EXPECT() *MockContextMockRecorder {
	return m.recorder
}

// Bot mocks base method.
func (m *MockContext) Bot() *tgbotapi.BotAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bot")
	ret0, _ := ret[0].(*tgbotapi.BotAPI)
	return ret0
}

// Bot indicates an expected call of Bot.
func (mr *MockContextMockRecorder) Bot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bot", reflect.TypeOf((*MockContext)(nil).Bot))
}

// Chat mocks base method.
func (m *MockContext) Chat() *tgbotapi.Chat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat")
	ret0, _ := ret[0].(*tgbotapi.Chat)
	return ret0
}

// Chat indicates an expected call of Chat.
func (mr *MockContextMockRecorder) Chat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockContext)(nil).Chat))
}

// ChatID mocks base method.
func (m *MockContext) ChatID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// ChatID indicates an expected call of ChatID.
func (mr *MockContextMockRecorder) ChatID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatID", reflect.TypeOf((*MockContext)(nil).ChatID))
}

// Get mocks base method.
func (m *MockContext) Get(key string) any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(any)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockContextMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockContext)(nil).Get), key)
}

// Message mocks base method.
func (m *MockContext) Message() *tgbotapi.Message {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Message")
	ret0, _ := ret[0].(*tgbotapi.Message)
	return ret0
}

// Message indicates an expected call of Message.
func (mr *MockContextMockRecorder) Message() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Message", reflect.TypeOf((*MockContext)(nil).Message))
}

// Reply mocks base method.
func (m *MockContext) Reply(arg0 string) (tgbotapi.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reply", arg0)
	ret0, _ := ret[0].(tgbotapi.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reply indicates an expected call of Reply.
func (mr *MockContextMockRecorder) Reply(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reply", reflect.TypeOf((*MockContext)(nil).Reply), arg0)
}

// ReplyHTML mocks base method.
func (m *MockContext) ReplyHTML(arg0 string) (tgbotapi.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplyHTML", arg0)
	ret0, _ := ret[0].(tgbotapi.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplyHTML indicates an expected call of ReplyHTML.
func (mr *MockContextMockRecorder) ReplyHTML(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplyHTML", reflect.TypeOf((*MockContext)(nil).ReplyHTML), arg0)
}

// ReplyWithMenu mocks base method.
func (m *MockContext) ReplyWithMenu(arg0 string, arg1 any) (tgbotapi.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplyWithMenu", arg0, arg1)
	ret0, _ := ret[0].(tgbotapi.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplyWithMenu indicates an expected call of ReplyWithMenu.
func (mr *MockContextMockRecorder) ReplyWithMenu(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplyWithMenu", reflect.TypeOf((*MockContext)(nil).ReplyWithMenu), arg0, arg1)
}

// ReplyWithMenuHTML mocks base method.
func (m *MockContext) ReplyWithMenuHTML(arg0 string, arg1 any) (tgbotapi.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplyWithMenuHTML", arg0, arg1)
	ret0, _ := ret[0].(tgbotapi.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplyWithMenuHTML indicates an expected call of ReplyWithMenuHTML.
func (mr *MockContextMockRecorder) ReplyWithMenuHTML(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplyWithMenuHTML", reflect.TypeOf((*MockContext)(nil).ReplyWithMenuHTML), arg0, arg1)
}

// Sender mocks base method.
func (m *MockContext) Sender() *tgbotapi.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sender")
	ret0, _ := ret[0].(*tgbotapi.User)
	return ret0
}

// Sender indicates an expected call of Sender.
func (mr *MockContextMockRecorder) Sender() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sender", reflect.TypeOf((*MockContext)(nil).Sender))
}

// Set mocks base method.
func (m *MockContext) Set(key string, val any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", key, val)
}

// Set indicates an expected call of Set.
func (mr *MockContextMockRecorder) Set(key, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockContext)(nil).Set), key, val)
}

// SetDisableWebPreviewForShortMethods mocks base method.
func (m *MockContext) SetDisableWebPreviewForShortMethods(arg0 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDisableWebPreviewForShortMethods", arg0)
}

// SetDisableWebPreviewForShortMethods indicates an expected call of SetDisableWebPreviewForShortMethods.
func (mr *MockContextMockRecorder) SetDisableWebPreviewForShortMethods(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDisableWebPreviewForShortMethods", reflect.TypeOf((*MockContext)(nil).SetDisableWebPreviewForShortMethods), arg0)
}

// Text mocks base method.
func (m *MockContext) Text() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Text")
	ret0, _ := ret[0].(string)
	return ret0
}

// Text indicates an expected call of Text.
func (mr *MockContextMockRecorder) Text() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Text", reflect.TypeOf((*MockContext)(nil).Text))
}

// Upd mocks base method.
func (m *MockContext) Upd() *tgbotapi.Update {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upd")
	ret0, _ := ret[0].(*tgbotapi.Update)
	return ret0
}

// Upd indicates an expected call of Upd.
func (mr *MockContextMockRecorder) Upd() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upd", reflect.TypeOf((*MockContext)(nil).Upd))
}
