name: Unit tests

on:
  push:
    branches:
        - '**'
  pull_request:

jobs:
  build:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: './go.mod'
      id: go

    - name: Build
      run: go build -v .

    - name: Run coverage
      run: go test -race -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: eli-l/telestage